# Generated by Django 4.0.2 on 2022-03-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_freature_image_alter_review_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='freature_image',
            new_name='featured_image',
        ),
    ]
